services:
  redis_dev:
    image: redis:alpine
    restart: always

  db_dev:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=sarker_dev
      - POSTGRES_USER=sarker_dev_user
      - POSTGRES_PASSWORD=sarker_dev_pass
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    networks:
      default:
        aliases:
          - backend # Inside the 'dev' project, this IS the backend
    environment:
      - REDIS_URL=redis://redis_dev:6379/0
      - DATABASE_URL=postgres://sarker_dev_user:sarker_dev_pass@db_dev:5432/sarker_dev
      - DEBUG=True
      - DOMAIN=dev.sarker.shop
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=https://dev.sarker.shop
    env_file:
      - ./backend/.env
    depends_on:
      - redis_dev
      - db_dev

  frontend_dev:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:80"
    depends_on:
      - backend_dev

volumes:
  postgres_data_dev:
