services:
  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=sarker_dev
      - POSTGRES_USER=sarker_user
      - POSTGRES_PASSWORD=sarker_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://sarker_user:sarker_pass@db:5432/sarker_dev
      - DEBUG=False
      - SECRET_KEY=django-insecure-dev-secret-key-change-this-in-prod
      - DOMAIN=dev.sarker.shop
      - ALLOWED_HOSTS=dev.sarker.shop,www.dev.sarker.shop,backend
      - CSRF_TRUSTED_ORIGINS=https://dev.sarker.shop,https://www.dev.sarker.shop
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: /usr/local/bin/uv run celery -A ecommerce_api worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://sarker_user:sarker_pass@db:5432/sarker_dev
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:80"
    environment:
      - VITE_API_URL=https://dev.sarker.shop/api
    depends_on:
      - backend

volumes:
  postgres_data:
