# Generated by Django 5.2.8 on 2026-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_guest_id_message_guest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
