# Generated by Django 5.2.8 on 2026-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount_price_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='e.g. 6GB, 128GB, Blue, 5000mAh', max_length=500),
        ),
    ]
