# Generated by Django 5.2.8 on 2026-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(help_text='e.g. RAM, Storage, Color, Battery', max_length=100),
        ),
    ]
