# Generated by Django 5.2.8 on 2026-04-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('export_product', 'Can export and import products')]},
        ),
    ]
