# Generated by Django 5.2.8 on 2026-04-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('export_import', 'Can manage data export and import')]},
        ),
    ]
