"""
Django settings for ecommerce_api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-16m5sa@!uf8bl7l91hd_ynkgn$qqij-ar5%-j^i%bp32#7j#=k')

# SECURITY WARNING: don't run with debug turned on in production!
def _bool(val, default):
    if val is None: return default
    return str(val).lower() in ['true', '1', 'yes', 't', 'y']

DEBUG = _bool(os.getenv('DEBUG'), True)

# =========================
# Cloudflare / Proxy Fix
# =========================
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True



# Application definition

INSTALLED_APPS = [
    'daphne',
    # 'unfold',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework_simplejwt',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_spectacular',

    # Custom apps
    'smart_selects',
    'accounts',
    'orders',
    'products',
    'reviews',
    'web',
    'api',

    # Social Login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'django_celery_results',
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1


REST_FRAMEWORK = {
    # 1. Authentication
    # We only use JWT. This ensures your API is stateless and secure.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 2. For Web Browsers / DRF Admin UI (Stateful)
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),

    # 2. Permissions
    # By default, anyone can Read (GET), but only Authenticated users can Write (POST/PUT/DELETE)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),

    # 3. Pagination (Crucial for performance)
    # Instead of loading 5,000 products at once, it sends 20 per page.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # 4. Filtering
    # This enables the ?category=mobile logic globally
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    # Optional: Date format for your JSON responses (YYYY-MM-DD)
    'DATE_INPUT_FORMATS': ["%Y-%m-%d"],

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',  # <--- Crucial for files
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Sarker Shop API',
    'DESCRIPTION': 'Comprehensive E-commerce API documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'OAUTH2_PASSWORD_FLOW': {
        'TOKEN_URL': '/api/token/',
        'REFRESH_URL': '/api/token/refresh/',
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),     # 1 day of uninterrupted browsing
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Stay logged in for a week
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ecommerce_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================
# ALLOWED HOSTS
# =========================
_allowed_hosts = os.getenv('ALLOWED_HOSTS', 'sarker.shop,www.sarker.shop,dev.sarker.shop,localhost,127.0.0.1,backend,*')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',')]
if '*' in ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

# =========================
# CORS (Frontend Access)
# =========================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost",
    "http://127.0.0.1",
    "https://sarker.shop",
    "https://www.sarker.shop",
    "https://dev.sarker.shop",
]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True


# =========================
# CSRF (Admin / Cookies)
# =========================
_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://sarker.shop,https://www.sarker.shop,https://dev.sarker.shop')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',')]

# Add local origins for development
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # Allows frontend to read cookie for CSRF header
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# 1. The URL prefix for static files
STATIC_URL = '/static/'

# 2. Where 'collectstatic' will put all your files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 3. Additional locations for static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


STORAGES = {
    # 1. Default storage (for user-uploaded files like product images/orders)
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # 2. Static files storage (for CSS/JS via WhiteNoise)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/'
API_BASE_URL = "http://127.0.0.1:8000/api"
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
BACKEND_URL = os.getenv('BACKEND_URL', f"https://{os.getenv('DOMAIN', 'sarker.shop')}")

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'sarker-shop-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'sarker-shop-refresh-token',
}

# Email Backend (SMTP for Production)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.hostinger.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Sarker Shop <info@sarker.shop>')

# Security settings - mutually exclusive
# Use SSL for port 465, TLS for 587
def _bool(val, default):
    if val is None: return default
    return str(val).lower() in ['true', '1', 'yes', 't', 'y']

if EMAIL_PORT == 465:
    EMAIL_USE_SSL = _bool(os.getenv('EMAIL_USE_SSL'), True)
    EMAIL_USE_TLS = False
else:
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = _bool(os.getenv('EMAIL_USE_TLS'), True)

# Allauth / Social Account Settings
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Changed from 'none' to 'optional'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

# Modern field configuration (silences deprecation warnings)
ACCOUNT_SIGNUP_FIELDS = {
    'username': {'required': False},
    'email': {'required': True},
    'password1': {'required': True},
    'password2': {'required': True},
}
ACCOUNT_USER_MODEL_UNIQUE_EMAIL = True
ACCOUNT_MAX_EMAIL_ADDRESSES = 1

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.MySocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_SECRET', ''),
            'key': ''
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id', 'first_name', 'last_name', 'middle_name', 'name', 
            'name_format', 'picture', 'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
}

# ========================
# Celery Configuration
# ========================
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'

# ========================
# Real-time Configuration
# ========================
ASGI_APPLICATION = 'ecommerce_api.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_URL', 'redis://redis:6379/0')],
        },
    },
}
