# Generated by Django 6.0.6 on 2026-06-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tv', '0002_category_remove_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='live_tv.category'),
        ),
    ]
