# Generated by Django 5.2.8 on 2026-04-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_notification_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Sarker Shop', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='web/logo/')),
                ('currency', models.CharField(default='BDT', max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
