# Generated by Django 5.2.8 on 2026-04-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_storeconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='web/favicon/'),
        ),
    ]
