# Generated by Django 5.2.8 on 2026-04-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_storeconfiguration_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storeconfiguration',
            name='currency',
            field=models.CharField(blank=True, default='BDT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storeconfiguration',
            name='website_name',
            field=models.CharField(blank=True, default='Sarker Shop', max_length=255, null=True),
        ),
    ]
