# Generated by Django 5.2.8 on 2026-04-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_storeconfiguration_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='dashboard_logo',
            field=models.ImageField(blank=True, null=True, upload_to='web/logo/'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='web/logo/'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to='web/logo/'),
        ),
    ]
