# Generated by Django 5.2.8 on 2026-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_storeconfiguration_dashboard_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='currency_symbol',
            field=models.CharField(blank=True, default='৳', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='messenger_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Dhaka', max_length=100, null=True),
        ),
    ]
