# Generated by Django 5.2.8 on 2026-04-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_storeconfiguration_currency_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='logo',
        ),
    ]
