# Generated by Django 5.2.8 on 2026-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_storeconfiguration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfiguration',
            name='whatsapp_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
