# Generated by Django 5.2.8 on 2026-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_storeconfiguration_whatsapp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='show_website_name',
            field=models.BooleanField(default=False),
        ),
    ]
