# Generated by Django 5.2.8 on 2026-04-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_storeconfiguration_show_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='is_cod_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='is_online_payment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='nagad_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='rocket_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
