# Generated by Django 5.2.8 on 2026-04-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_storeconfiguration_bkash_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='stripe_public_key',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='stripe_secret_key',
        ),
    ]
