# Generated by Django 5.2.8 on 2026-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devfeedback',
            name='type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('bug', 'Bug'), ('ui', 'UI'), ('performance', 'Performance'), ('security', 'Security'), ('suggestion', 'Suggestion')], max_length=20),
        ),
    ]
